#!/usr/bin/env python3
"""api_demo.py - Tests the Hub Server via multiple HTTP execution calls."""

import asyncio
import httpx
from httpx_sse import aconnect_sse
from pathlib import Path
import json

HUB_URL = "http://localhost:8001"


async def listen_to_events(stop_event: asyncio.Event, expected_completions: int):
    """Connects to the SSE stream and prints events as they happen."""
    completed_graphs = 0
    try:
        async with httpx.AsyncClient(timeout=httpx.Timeout(30.0, connect=10.0)) as client:
            print(f"🔌 Connecting to Event Stream at {HUB_URL}/events...")
            async with aconnect_sse(client, "GET", f"{HUB_URL}/events") as event_source:
                async for sse in event_source.aiter_sse():
                    if sse.event == "ping":
                        continue
                    print(f"\n🔔 [SSE Event] {sse.event.upper()}")

                    try:
                        payload = json.loads(sse.data)
                        print(f"   Payload: {json.dumps(payload, indent=2)}")
                    except json.JSONDecodeError:
                        print(f"   Payload: {sse.data}")

                    if sse.event == "agent:completed" or sse.event == "agent:failed":
                        completed_graphs += 1
                        if completed_graphs >= expected_completions:
                            print("\n🛑 Received all expected agent completions. Terminating monitor.")
                            stop_event.set()
                            break
    except httpx.ReadTimeout:
        print("⏱️ Event stream timed out waiting for events")
    except Exception as e:
        if not stop_event.is_set():
            print(f"❌ Event Stream Error: {e}")
        stop_event.set()


async def trigger_execution(agent_bundle: str, file_path: str, target_code: str):
    """Fire-and-forget: POST to start agent, return immediately with graph_id."""
    payload = {"bundle": agent_bundle, "target_path": file_path, "target": target_code}

    print(f"\n🚀 Fire-and-forget: POST for '{agent_bundle}' bundle...")
    try:
        async with httpx.AsyncClient(timeout=httpx.Timeout(5.0, connect=3.0)) as client:
            response = await client.post(f"{HUB_URL}/graph/execute", json=payload)

            if response.status_code == 200:
                data = response.json()
                graph_id = data.get("graph_id")
                print(f"✅ Started! Graph ID: {graph_id}")
                return graph_id
            else:
                print(f"❌ HTTP Error: {response.status_code} - {response.text}")
                return None
    except Exception as e:
        print(f"❌ Request failed: {e}")
        return None


async def poll_for_completion(graph_ids: list[str], timeout: float = 30.0):
    """Poll /graph/list until all graphs are done."""
    print(f"\n📋 Polling for completion of graphs: {graph_ids}")
    start = asyncio.get_event_loop().time()

    async with httpx.AsyncClient(timeout=httpx.Timeout(10.0)) as client:
        while asyncio.get_event_loop().time() - start < timeout:
            try:
                response = await client.get(f"{HUB_URL}/graph/list")
                if response.status_code == 200:
                    graphs = response.json().get("graphs", [])
                    running = [g for g in graphs if g.get("graph_id") in graph_ids and g.get("status") == "running"]
                    if not running:
                        print(f"✅ All graphs completed!")
                        return True
                    print(f"   Still running: {len(running)} graphs...")
            except Exception as e:
                print(f"   Poll error: {e}")

            await asyncio.sleep(1)

    print("⏱️ Timeout waiting for completion")
    return False


async def list_files():
    """Demonstrates listing the workspace generated by the server via HTTP."""
    print("\n📂 Fetching workspace state...")
    async with httpx.AsyncClient() as client:
        response = await client.get(f"{HUB_URL}/api/files?path=")
        if response.status_code == 200:
            data = response.json()
            entries = data.get("entries", [])
            print(f"   Found {len(entries)} workspace(s):")
            for e in entries:
                print(f"   - {e.get('name')} ({e.get('type')})")


async def main():
    print("=" * 70)
    print("🌐 REMORA MULTI-AGENT HTTP CLIENT DEMO")
    print("   (Fire-and-Forget Pattern)")
    print("=" * 70)

    stop_event = asyncio.Event()

    listener_task = asyncio.create_task(listen_to_events(stop_event, expected_completions=2))

    await asyncio.sleep(0.5)

    graph_ids = []

    gid = await trigger_execution(
        agent_bundle="simple_analyzer",
        file_path="demo_input/src/main.py",
        target_code="def calculate_sum(a, b):\n    result = a + b\n    return result",
    )
    if gid:
        graph_ids.append(gid)

    await asyncio.sleep(0.2)

    gid = await trigger_execution(
        agent_bundle="simple_analyzer",
        file_path="demo_input/src/utils/helpers.py",
        target_code='def format_greeting(name: str) -> str:\n    return f"Hello, {name}!"',
    )
    if gid:
        graph_ids.append(gid)

    print(f"\n⏳ Started {len(graph_ids)} graphs. Listening for events...\n")

    await stop_event.wait()

    await list_files()

    print("\n" + "=" * 70)
    print("🎉 CLIENT DEMO COMPLETE")
    print("=" * 70)


if __name__ == "__main__":
    asyncio.run(main())
