# Auto-generated by grail — do not edit

from typing import Any

issue_code: str
line_number: int
target_file_input: str | None

async def read_file(path: str) -> str:
    """Read the text contents of a file."""
    ...

async def file_exists(path: str) -> bool:
    """Check if a file or directory exists."""
    ...

async def run_command(cmd: str, args: list[str]) -> dict[str, Any]:
    """Run a command in the sandbox."""
    ...
