# Auto-generated by grail — this is what Monty actually executes

_ = noop

def _extract_tool_section(content: str, section: str) -> str:
    lines = content.splitlines()
    header = f'[{section}]'
    start_index = None
    for idx, line in enumerate(lines):
        if line.strip() == header:
            start_index = idx
            break
    if start_index is None:
        return ''
    collected = [lines[start_index]]
    for line in lines[start_index + 1:]:
        if line.startswith('[') and line.strip().endswith(']'):
            break
        collected.append(line)
    return '\n'.join(collected).strip()
try:
    if await file_exists(path='pytest.ini'):
        result = await read_file(path='pytest.ini')
    elif await file_exists(path='pyproject.toml'):
        content = await read_file(path='pyproject.toml')
        result = _extract_tool_section(content, 'tool.pytest.ini_options')
    else:
        result = ''
except Exception:
    result = ''
result