"""Protocol surface used by LSP handler modules.

Handlers depend on this protocol instead of importing ``remora.lsp.server``
directly, which avoids creating a server<->handlers import cycle.
"""

from __future__ import annotations

from typing import Any, Protocol


class LspServer(Protocol):
    event_store: Any
    db: Any
    proposals: dict[str, Any]
    runner: Any
    workspace: Any
    protocol: Any

    def command(self, command_name: str): ...
    def feature(self, feature_name: str): ...

    def generate_correlation_id(self) -> str: ...
    def note_user_activity(self, source: str = "unknown") -> None: ...
    def schedule_reparse(self, uri: str, text: str, delay_ms: int = 500) -> None: ...
    def schedule_cursor_update(self, agent_id: str | None, uri: str, line: int, delay_ms: int = 200) -> None: ...
    def window_show_message(self, params: Any) -> None: ...

    async def workspace_apply_edit(self, params: Any) -> Any: ...
    async def refresh_code_lenses(self) -> None: ...
    async def publish_diagnostics(self, uri: str, proposals: list[Any]) -> None: ...
    async def emit_event(self, event: Any) -> Any: ...
    async def notify_agents_updated(self) -> None: ...
    async def accept_proposal(self, proposal_id: str) -> None: ...

