# Auto-generated by grail — do not edit

node_text_input: str | None
target_file_input: str | None

async def read_file(path: str) -> str:
    """Read the text contents of a file."""
    ...

async def file_exists(path: str) -> bool:
    """Check if a file or directory exists."""
    ...
